package com.mams.audit;

public enum AuditAction {
    PURCHASE_CREATED,
    TRANSFER_CREATED,
    TRANSFER_APPROVED,
    TRANSFER_COMPLETED,
    TRANSFER_CANCELLED,
    ASSIGNMENT_CREATED,
    EXPENDITURE_CREATED,
    USER_CREATED,
    USER_UPDATED,
    INVENTORY_UPDATED,
    BASE_CREATED,
    BASE_UPDATED,
    EQUIPMENT_CREATED,
    EQUIPMENT_UPDATED
}
